# Generated by Django 4.1 on 2024-01-02 14:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brReceipt', '0002_rename_recipe_receipt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipt',
            new_name='Receipe',
        ),
    ]
