# Generated by Django 4.1 on 2024-01-04 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brReceipt', '0005_ratescategory_ratesreceipt_receipt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='receipt',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brReceipt.category'),
        ),
    ]
