# Generated by Django 4.1 on 2024-01-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brReceipt', '0006_rename_title_receipt_name_receipt_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratescategory',
            old_name='category',
            new_name='id_category',
        ),
        migrations.RenameField(
            model_name='ratescategory',
            old_name='user',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='ratesreceipt',
            old_name='receipt',
            new_name='id_receipt',
        ),
        migrations.RenameField(
            model_name='ratesreceipt',
            old_name='user',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='author',
            new_name='id_author',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='category',
            new_name='id_category',
        ),
    ]
